let
    Source = cdesk_fnGetAllPages("customer"),
    #"Converted to Table" = Table.FromList(Source, Splitter.SplitByNothing(), null, null, ExtraValues.Error), 
    #"Expanded Column1" = Table.ExpandRecordColumn(#"Converted to Table", "Column1", {"id", "name", "alias", "customer", "status", "email_general", "phone_general", "mobile_general", "street", "city", "zip", "country", "ico", "dic", "icdph", "properties", "customer-category", "customer-type"}, {"id", "name", "alias", "customer", "status", "email_general", "phone_general", "mobile_general", "street", "city", "zip", "country", "ico", "dic", "icdph", "properties", "customer-category", "customer-type"}),
    #"Parsed Fields" = Table.AddColumn(#"Expanded Column1", "Fields", each 
        if [properties] is list then 
            let
                CleanList = List.Transform([properties], (p) => 
                    let 
                        Raw = p[values]?{0}?[baseproperties]?{0}?[value]?
                    in
                        [
                            Name = p[name], 
                            Value = if Raw is list then Text.Combine(List.Transform(Raw, each Text.From(_)), ", ") 
                                    else if Raw = null then "" 
                                    else Text.From(Raw)
                        ]
                ),
                AsRecord = Record.FromList(
                    List.Transform(CleanList, each _[Value]), 
                    List.Transform(CleanList, each _[Name])
                )
            in
                AsRecord
        else 
            null
    ),
    #"Expanded Fields" = Table.ExpandRecordColumn(#"Parsed Fields", "Fields", 
        {   "Ignoruj?", "Krádež vozidla?", "Obchodník", "Poznámka Dispečing NEW", "Replay kód", "GPS kód", "ŠPZ", 
            "Typ vozidla", "Heslo", "XTyp zákazníka", "Dátum pripojenia na PCO/Montáže", "Dátum odpojenia od PCO Demontáže", 
            "Master kód", "Typy objektov", "Výjazdová firma", "Nové heslo - nepotvrdené", "Zástupcovia HESLO", 
            "Komunikátor", "Poloha", "Kraj", "Okres", "kód SeS", "Dátum krádeže", "Otváracia doba Pondelok:", 
            "Otváracia doba Utorok:", "Otváracia doba Streda:", "Otváracia doba Štvrtok:", "Otváracia doba Piatok:",
            "Otváracia doba Sobota:", "Otváracia doba Nedeľa:", "projekt_výkres", "Výjazdový plán", "Typ alarmu", 
            "Druh vozidla", "Farba vozidla", "Spínač", "Uložené v sektore", "V C motora", "V C karosérie", 
            "XTechnici", "Montér", "Number Box", "MontAlarm?", "Pánik?", "Miesto parkovania", "Poisťovňa", 
            "Číslo zákazníka", "1.Skontrolovane?", "2.Je zmluva?", "3.Je nová zmluva?", "Montážny list umiestnenie",
            "SZ", "NZ", "Dátum starej zmluvy", "Dátum novej zmluvy", "Dátum demontáže od", "Dátum demontáže do", 
            "Dátum UZOD", "ID v starej DB", "ID dočasná demontáž v starej DB", "ID neplatné v starej DB", 
            "Nesúhlas marketingové účely?", "Typ mobilnej jednotky"
        }),
    #"Removed Original List" = Table.RemoveColumns(#"Expanded Fields", {"properties"}),
    #"TypeDateTime" = Table.TransformColumnTypes(#"Removed Original List",{{"Dátum pripojenia na PCO/Montáže", type datetime}, {"Dátum odpojenia od PCO Demontáže", type datetime}, {"Dátum krádeže", type datetime}, {"Dátum starej zmluvy", type datetime}, {"Dátum novej zmluvy", type datetime}, {"Dátum demontáže od", type datetime}, {"Dátum demontáže do", type datetime}, {"Dátum UZOD", type datetime}})
in
    #"TypeDateTime"
